### PR TITLE
Allow `/quit` with a message

### PR DESCRIPTION
**Pull request by ALEX11BR**
Addresses issue #1.

### CODE REVIEW

**Comment by alexandruradovici** [comment]
Please force push this again, I activated the workflows and this is probably one way of making them run.

**Review by alexandruradovici — APPROVED** [review]
I think this is ready to be sent upstream. Please write a PR message in a comment so that we can review that before sending ti upstream.

**Comment by ALEX11BR** [comment]
This pull request adds an optional message parameter to the `/quit` command to be sent to the connected servers as a reason for leaving.

This pull request was tested by using a tiny and a different IRC client, both connected to the same server.

Fixes #365.

**Comment by alexandruradovici** [comment]
I updated your PR text, I think this is ready to be opened to upstream.

**Comment by alexandruradovici** [comment]
Please force push the last commit again to run the tests (`git push --force`).

**Comment by ALEX11BR** [comment]
```
 ~/Public/tiny on   alex11br ❯ git push --force  
Everything up-to-date
 ~/Public/tiny on   alex11br ❯ 
```
can't push

**Comment by alexandruradovici** [comment]
Make a small change in a comment and push it.

**Comment by alexandruradovici** [comment]
Looks good, please write a pull request message explaining what you did and post it here.

**Comment by ALEX11BR** [comment]
Added the ability to parse the parameters of the /quit and send them as a reason for leaving the application to the connected servers

**Comment by alexandruradovici** [comment]
Opened PR https://github.com/osa1/tiny/pull/395

**Comment by ALEX11BR** [comment]
As the original author of the project suggested, I also added the same thing for the `/close` command, and the changes are now merged. Yay!

**Comment by alexandruradovici** [comment]
Closing as it was merge to the upstream.

**Comment by alexandruradovici** [comment]
Well done.

**Pull request closed without merging**
